version: '3.7'

services:
  progressus-app:
    networks:
      - progressus-network
    links:
      - progressus-db
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    env_file:
      - .env
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev

  progressus-db:
    networks:
      - progressus-network
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

networks:
  progressus-network:
    driver: bridge